In [74]:
import numpy as np
from scipy.linalg import orth
from scipy.misc import imread
import sympy

In [35]:
v1 = np.array([1,2,3,4])
v2 = np.array([0,1,0,1])
v3 = np.array([1,4,3,6])
v4 = np.array([2,11,6,15])
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html
matrix = np.vstack((v1,v2,v3,v4))
print(matrix)
#http://docs.sympy.org/dev/tutorial/matrices.html
reduce = sympy.Matrix(matrix).rref()
print(reduce)

[[ 1  2  3  4]
 [ 0  1  0  1]
 [ 1  4  3  6]
 [ 2 11  6 15]]
(Matrix([
[1.0,   0, 3.0, 2.0],
[  0, 1.0,   0, 1.0],
[  0,   0,   0,   0],
[  0,   0,   0,   0]]), [0, 1])


In [37]:
#Problem 1 number 1
not_in_s = np.array([3,17,6,9])
matrix2 = np.vstack((matrix,not_in_s))
reduce2 = sympy.Matrix(matrix2).rref()
print(reduce2)
#because reduced matrix changed vector not_in_s is not in s
#to check if a vector is in s we would add it to the matrix and see if the 
#reduced matrix equaled the original reduced matrix

[[ 1  2  3  4]
 [ 0  1  0  1]
 [ 1  4  3  6]
 [ 2 11  6 15]
 [ 2  4  6  8]]
(Matrix([
[1.0,   0, 3.0, 2.0],
[  0, 1.0,   0, 1.0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0]]), [0, 1])


In [39]:
in_s = np.array([2,6,6,10])
matrix3 = np.vstack((matrix, in_s))
reduce3 = sympy.Matrix(matrix3).rref()
print(reduce3)
#because vector new vector is in span rref does not change from original

(Matrix([
[1.0,   0, 3.0, 2.0],
[  0, 1.0,   0, 1.0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0]]), [0, 1])


In [31]:
#Problem 1 number 2
print(np.linalg.matrix_rank(matrix))

2


In [23]:
#Problem 1 number 3
print(orth(matrix))

[[-0.24011927  0.8581727 ]
 [-0.05990306 -0.29094143]
 [-0.35992538  0.27628983]
 [-0.89955994 -0.32024463]]


In [70]:
#Problem 1 number 4
z = np.array([1,0,0,0])
matrix4 = np.vstack((v1,v2)).transpose()
matrix5 = (matrix4.transpose().dot(matrix4))
matrix6 = matrix5.dot(matrix4.transpose())
minx_s = matrix6[:, 0]
print(minx_s)
#print(np.linalg.inv(matrix5))
#print(matrix4 * matrix4.transpose())
#print(np.linalg.inv((matrix4.transpose() * matrix4)))

[30  6]


In [ ]:
#http://sebastianraschka.com/Articles/2014_pca_step_by_step.html

In [76]:
mona_lisa = imread('../Downloads/mona_lisa.png')

FileNotFoundError: [Errno 2] No such file or directory: '../Downloads/mona_lisa'